### ISSUE TITLE
Failed to insert new document - An equivalent index already exists

### ISSUE THREAD

**Issue by m8r1us** [Azure/Stormspotter#7]
Hi

Thank you for the Stormspotter tool. 

I try to run the tool in my test lab:
Windows 10
neo4j 4.0
Python 3.8

Collection with stormspotter worked well.
But when I run the cmd: stormdash -dbu neo4j -dbp 
I get the following error:

```
Connecting to bolt://localhost:7687
Running on http://127.0.0.1:8050/
Debugger PIN: 848-976-926
 * Serving Flask app "Stormdash" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
Connecting to bolt://localhost:7687
CREATE INDEX ON : AADApplication(id)
[=] Failed to insert new document
trying to reconnect to bolt server
Traceback (most recent call last):
  File "C:\AzureAssessment\Stormspotter-master\stormspotter\dash\core\neo4j.py", line 149, in query
    result = session.run(statement)
  File "C:\Python\Python38-32\lib\site-packages\neo4j\__init__.py", line 503, in run
    self._connection.fetch()
  File "C:\Python\Python38-32\lib\site-packages\neobolt\direct.py", line 419, in fetch
    return self._fetch()
  File "C:\Python\Python38-32\lib\site-packages\neobolt\direct.py", line 461, in _fetch
    response.on_failure(summary_metadata or {})
  File "C:\Python\Python38-32\lib\site-packages\neobolt\direct.py", line 755, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.ClientError: An equivalent index already exists, 'Index( 1, 'index_9b31a2b5', GENERAL BTREE, :AADApplication(id), native-btree-1.0 )'.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\AzureAssessment\Stormspotter-master\Stormdash.py", line 175, in <module>
    main()
  File "C:\AzureAssessment\Stormspotter-master\Stormdash.py", line 171, in main
    parser = DashParser(args.dbuser, args.dbpass, args.db)
  File "C:\AzureAssessment\Stormspotter-master\stormspotter\dash\core\context.py", line 19, in __init__
    self.neo = Neo4j(user=user, password=password, server=server)
  File "C:\AzureAssessment\Stormspotter-master\stormspotter\dash\core\neo4j.py", line 31, in __init__
    self.create_indexes()
  File "C:\AzureAssessment\Stormspotter-master\stormspotter\dash\core\neo4j.py", line 98, in create_indexes
    self.query(statement)
  File "C:\AzureAssessment\Stormspotter-master\stormspotter\dash\core\neo4j.py", line 160, in query
    self.session.run(statement)
AttributeError: 'Neo4j' object has no attribute 'session'
Closing the neo4j session
```

Maybe already known?

Thank you

M

**Comment by m8r1us** [comment]
Works with Neo4j Community Edition 3.5.18
